/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * OEM Tracker frozen data contract. contract_version 1.0.0. One tidy row per observation (long format). The bundle is the artifact the UI reads. See docs/contract-coverage.md for the widget->field mapping and the non-negotiable rules.
 */
export interface Bundle {
  /**
   * Frozen contract version. Bump only on a breaking schema change.
   */
  contract_version: "1.0.0";
  /**
   * When this bundle was built. Injected by the builder; never derived from wall-clock inside pure logic.
   */
  generated_at: string;
  /**
   * Human label for share denominators. For SIAM: 'Share within reported SIAM universe'. Lives in the contract, never hardcoded in UI.
   */
  source_universe_label: string;
  /**
   * The tidy observation rows.
   */
  rows: ContractRow[];
}
/**
 * One observation. Long format: never one column per month. 0 and null are DISTINCT (0 = source-reported zero / not-launched; null = not reported). Never sum across inclusive dimension values (powertrain all>=ev; flow total>=domestic+export).
 */
export interface ContractRow {
  /**
   * First day of the period, e.g. 2026-06-01.
   */
  period_date: string;
  period_type: "month" | "quarter" | "year";
  /**
   * Fiscal year Apr-Mar, e.g. 'FY26' = Apr 2025 - Mar 2026.
   */
  fiscal_year: string;
  /**
   * e.g. 'Q1FY26' = Apr-Jun 2025. Null for yearly rows.
   */
  fiscal_quarter: string | null;
  /**
   * Vehicle category. A dimension, never an assumption. v1 seeds 2W but the contract holds all.
   */
  category: "2W" | "PV" | "3W" | "TRACTOR" | "CV";
  /**
   * e.g. 'Scooter', 'Motor cycles', 'Mopeds' (2W); 'PC', 'UV', 'Van' (PV); 'MHCV', 'LCV' (CV).
   */
  segment: string | null;
  sub_segment: string | null;
  /**
   * Resolved via dictionaries/companies.yaml.
   */
  company_canonical: string;
  /**
   * Exactly as it appeared in the source. Kept so a bad mapping is always traceable and reversible.
   */
  company_raw: string;
  /**
   * Different measurements, not variants of 'sales'. total >= domestic + export; never sum total with its parts.
   */
  flow: "domestic" | "export" | "production" | "total";
  /**
   * Source reports 'all' and 'ev' (ev is a SUBSET of all). 'ice' is DERIVED = all - ev. Never sum across these values.
   */
  powertrain: "all" | "ev" | "ice";
  geography: string;
  /**
   * What is measured. Extensible (e.g. 'value') later without a breaking change to consumers.
   */
  metric: "units";
  /**
   * The measurement. 0 and null are DISTINCT and must never be coerced into each other.
   */
  value: number | null;
  unit: "units";
  /**
   * On every row. Enforces the one-source-per-table rule and encodes measurement basis (SIAM=wholesale dispatches, VAHAN=registrations) via metrics.yaml.
   */
  source: "SIAM" | "VAHAN" | "BROKER" | "MANUAL";
  /**
   * The dropped source file this row came from (audit trail).
   */
  source_file: string;
  /**
   * The period the source file reports as-of.
   */
  source_period: string;
  /**
   * What the source ACTUALLY reported. CV is quarterly-native; everything else monthly-native.
   */
  native_frequency: "month" | "quarter" | "year";
  /**
   * reported = literal from source. derived = summed M->Q->Y OR ice = all - ev.
   */
  calc_status: "reported" | "derived";
  /**
   * 0,1,2... A newer file correcting an old period writes revision+1 and supersedes the old row.
   */
  revision: number;
  ingest_date: string;
  confidence: "high" | "medium" | "low";
  /**
   * True once a newer revision replaces this row. Never delete; always supersede.
   */
  is_superseded: boolean;
  /**
   * True for an incomplete period (YTD / QTD / running month). Drives the 'YTD'/'Quarter to date' labels.
   */
  is_partial: boolean;
  /**
   * Constituent sub-periods actually present in a derived aggregate (e.g. 2 months of a quarter). Null when reported/complete.
   */
  periods_present: number | null;
  /**
   * Constituent sub-periods a complete aggregate would have (e.g. 3 for a quarter). Null when reported/complete.
   */
  periods_expected: number | null;
}
